[package]
name = "CHIP8-Emulator"
version = "0.1.0"
authors = ["d4s3 <honeycutt.chandler@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
